# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'Assassin' do

pod ‘Firebase’, ‘>= 2.3.3’

end

target 'AssassinTests' do

end

target 'AssassinUITests' do

end

